# Generated by Django 3.2.16 on 2022-10-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField()),
                ('phoneNum', models.IntegerField()),
                ('address', models.CharField(max_length=255)),
                ('postalCode', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('pickupTime', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ok', 'Ok'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=255)),
            ],
        ),
    ]
