# Generated by Django 3.2.16 on 2022-10-17 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ordercard'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=50)),
                ('nif', models.IntegerField()),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('token', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=False)),
                ('createdDate', models.DateField()),
                ('last_login', models.DateField()),
                ('updatedDate', models.DateField()),
            ],
        ),
    ]
