# Generated by Django 3.2.16 on 2022-10-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20221017_1028'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=550)),
            ],
        ),
        migrations.AddField(
            model_name='uploadinsurance',
            name='insurance_end_date',
            field=models.CharField(default=2019, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currentuser',
            name='password',
            field=models.CharField(max_length=550),
        ),
        migrations.AlterField(
            model_name='currentuser',
            name='username',
            field=models.CharField(max_length=550),
        ),
    ]
