# Generated by Django 3.2.16 on 2022-10-19 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentuser',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='currentuser',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
