# Generated by Django 3.2.16 on 2022-10-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20221019_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentuser',
            name='token',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='currentuser',
            name='username',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='email',
            name='password',
            field=models.CharField(max_length=500),
        ),
    ]
