# Generated by Django 3.2.16 on 2022-10-21 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20221020_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadinsurance',
            name='insurance_end_date',
            field=models.CharField(default=2017, max_length=150),
            preserve_default=False,
        ),
    ]
