# Generated by Django 3.2.16 on 2022-11-02 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20221021_1329'),
        ('core', '0008_uploadinsurance_insurance_end_date'),
    ]

    operations = [
    ]
