# Generated by Django 3.2.16 on 2022-11-03 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_merge_20221102_2132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentuser',
            name='nif',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='currentuser',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='currentuser',
            name='username',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='email',
            name='password',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='insurancetype',
            name='perDayPrice',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ordercard',
            name='phoneNum',
            field=models.IntegerField(max_length=225),
        ),
        migrations.AlterField(
            model_name='ordercard',
            name='user_id',
            field=models.IntegerField(max_length=225),
        ),
        migrations.AlterField(
            model_name='uploadinsurance',
            name='citizenCardNum',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='uploadinsurance',
            name='insurance_end_date',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='uploadinsurance',
            name='nif',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='uploadinsurance',
            name='user_id',
            field=models.IntegerField(max_length=225),
        ),
    ]
